---
server:
  port: 10002
spring:
  config:
    activate:
      on-profile:
      - build
  application:
    name: configclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
---
server:
  port: 10003
spring:
  config:
    activate:
      on-profile:
      - test
  application:
    name: configclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
---
server:
  port: 10004
spring:
  config:
    activate:
      on-profile:
      - dev
  application:
    name: configclient
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
---
