spring:
  config:
    activate:
      on-profile:
      - eureka-7001
server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表示是否向eureka注册自己
    fetch-registry: false #如果为false，则表示自己为注册服务中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #监控页面

#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  config:
    activate:
      on-profile:
      - eureka-7002
server:
  port: 7002
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表示是否向eureka注册自己
    fetch-registry: false #如果为false，则表示自己为注册服务中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #监控页面

#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
spring:
  config:
    activate:
      on-profile:
      - eureka-7003
server:
  port: 7003
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #表示是否向eureka注册自己
    fetch-registry: false #如果为false，则表示自己为注册服务中心
    service-url:
      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/ #监控页面

#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
---
