spring:
  profiles:
    active: dev
---
server:
  port: 10002
spring:
  profile: dev
  application:
    name: springcloud-provider-dept
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
---
server:
  port: 10003
spring:
  profile: test
  application:
    name: springcloud-provider-dept
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
---
server:
  port: 10004
spring:
  profile: build
  application:
    name: springcloud-provider-dept
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/