server:
  port: 8001
mybatis:
  type-aliases-package: com.std.springcloud.pojo
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring:
  config:
    activate:
      on-profile:
      - provider-8001
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&Timezone=UTC
    username: root
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
  instance:
    instance-id: springcloud-provider-8001-dept
management:
  endpoints:
    web:
      exposure:
        # 打开所有的监控点
        include: health,info
      # 自定义监控路径 monitor
      # 默认值：http://localhost:8016/actuator/*
      # 配置后：http://localhost:8016/monitor/*
  endpoint:
    health:
      show-details: always
    shutdown:
      # 通过指定接口关闭 SpringBoot
      enabled: true
  info:
    env:
      enabled: true   #需要开启info


# 描述项目基础信息
info:
  app:
    name: springcloud-provider-8001
    port: 8001
    version: 1.0.0
    author: me